### ISSUE TITLE
permission not working

### ISSUE THREAD

**Issue by leandroruel** [yajra/laravel-acl#14]
i think i'm doing something wrong, not sure, i searched at stackoverflow but i not find anything related to this package, so i followed the installation tutorial at documentation, and inserted a admin permission to test a user, but even after that he keep returning "**You are not authorized to access this resource**."

i'm using a api route resource, like this:
```php
Route::group(['middleware' => ['auth:api', 'role:admin']], function() {
	Route::resource('users', User\UserController', ['except' => 'edit']);
});
```

this is my table: permissions
![permission-table](https://user-images.githubusercontent.com/2836002/30918324-98717eb2-a374-11e7-84c0-3cab87228c9c.png)
this is my tabke: permissions_role
![permissions-role-table](https://user-images.githubusercontent.com/2836002/30918376-c0657202-a374-11e7-844c-680e579dfdb5.png)

**Comment by yajra** [comment]
Did your inserted the records directly on database? The packages uses cache. Try clearing it first?

```bash
php artisan cache:clear
```

**Comment by leandroruel** [comment]
yes, cleaned all, just one question, can i use this package to block a route in a api?

**Comment by yajra** [comment]
I think YES, as long as the api routes are using the same `User` instance that implements the `HasRole` trait. 

Are you using passport or just the standard api route? Will double check when I got the chance.

**Comment by leandroruel** [comment]
i'm using passport with api routes

**Comment by yajra** [comment]
Please open a new ticket if needed. Thanks!
