### ISSUE TITLE
The user()->can($permission) is never called and not working

### ISSUE THREAD

**Issue by imranniaz** [yajra/laravel-acl#15]
### Summary of problem or feature request

I'm trying to access a route with given permission but it's not authorizing access
when i try to debug the method "Can" which is being called in the middleware
the method is never called from the HasPermission.

How to debug this issue?

```
class PermissionMiddleware
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure $next
     * @param  string $permission
     * @return mixed
     */
    public function handle($request, Closure $next, $permission)
    {

        if (! $request->user() || ! $request->user()->can($permission)) {
            if ($request->ajax()) {
                return response()->json([
                    'error' => [
                        'status_code' => 401,
                        'code'        => 'INSUFFICIENT_PERMISSIONS',
                        'description' => 'You are not authorized to access this resource.',
                    ],
                ], 401);
            }

            return abort(401, 'You are not authorized to access this resource.');
        }

        return $next($request);
    }
}
```

**Comment by imranniaz** [comment]
Also I'm wondering how the method "can" is being called over user()->can($permission) as this trait doesn't belong to user but to role.

**Comment by yajra** [comment]
`can` method is the built-in authorization of Laravel under `trait Authorizable`. Database policies are registered via service provider `AclServiceProvider`. 

Notes:
1. Make sure `AclServiceProvider` is properly loaded / installed.
2. The package uses cache. You may have to run `php artisan cache:clear` in some instances.
3. See [docs](https://yajrabox.com/docs/laravel-acl/master/middleware#permission) for ref.

**Comment by imranniaz** [comment]
Thanks Yajra, it worked with cache:clear
but still I have question: the can method in HasPermission trait is never called on user but other methods are called like getPermission which is in both HasRole and HasPermission trait.
