### ISSUE TITLE
intersect method removed from Laravel 5.5

### ISSUE THREAD

**Issue by leandroruel** [yajra/laravel-acl#17]
[the method intersect was deprecated in laravel 5.5](https://laravel.com/docs/5.5/upgrade)

**The intersect Method**

The intersect method has been removed. You may replicate this behavior using `array_filter` on a call to `$request->only:`

```php
return array_filter($request->only('foo'));
```

i see it being used here: https://github.com/yajra/laravel-acl/blob/3.0/src/Traits/HasRole.php#L69

**Comment by yajra** [comment]
Thanks for pointing this out. Would you mind submitting a PR to fix it?

**Comment by leandroruel** [comment]
looks like @lexf made a fix, this issue was seen in other acl packages too, so, thanks for this fix.
