### ISSUE TITLE
resource&system columns

### ISSUE THREAD

**Issue by Vuishnak** [yajra/laravel-acl#2]
For what this columns and how i can use them?

**Comment by yajra** [comment]
You can use resource column to authorize your resource controller. See this example controller where I authorize all the routes. https://github.com/yajra/cms-core/blob/master/src/Http/Controllers/ArticlesController.php#L25

```php
    public function __construct()
    {
        $this->authorizePermissionResource('article');
    }
```

You can use the system column, to protect the record from being deleted.

```php
if (! $per->system) {
 // allow delete
}
```

**Comment by yajra** [comment]
An actual use case for the system column can be found [here](https://github.com/yajra/cms-core/blob/master/src/resources/views/administrator/permissions/datatables/action.blade.php)

**Comment by Vuishnak** [comment]
thanks!

**Comment by orumad** [comment]
Hi Yajra, amazing package!

Maybe you can include those comments in the documentation?

Thanks!

**Comment by yajra** [comment]
@orumad thanks for the appreciation. You can also contribute in the docs via this [repo](https://github.com/yajra/laravel-acl-docs). Will update the docs when I had the chance. Thanks!
