### ISSUE TITLE
Migrations loaded doesn't allow to customize User model

### ISSUE THREAD

**Issue by leandrowferreira** [yajra/laravel-acl#26]
### Summary of problem or feature request
When `AclServiceProvider.php` calls the `loadMigrationsFrom()` method, the published migrations (that I changed to reflect a customized User model) will be overwrited by the original migration, stored at `yajra/laravel-acl/migrations`.

In my case, I have `Usuario` model instead of `User` model. The service respects the model assigned at `config/auth.php`, but the migration fixes internally it to `user`.

### Code snippet

**AclServiceProvider.php**
```php
    /**
     * Publish package migration files.
     */
    protected function publishMigrations()
    {
        $this->loadMigrationsFrom(__DIR__ . '/../migrations'); //This line could be removed
        $this->publishes([
            __DIR__ . '/../migrations' => database_path('migrations'),
        ], 'laravel-acl');
    }
```

**2015_12_20_100004_create_role_user_table.php**
```php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateRoleUserTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('role_user', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('role_id')->unsigned()->index();
            $table->foreign('role_id')->references('id')->on('roles')->onDelete('cascade');
            $table->integer('user_id')->unsigned()->index();
            $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migration.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('role_user');
    }
}
```
I would suggest to remove the indicated line at `AclServiceProvider.php` file.

**Comment by yajra** [comment]
Thanks for the suggestions but I think removing that line will then require every installation to publish the migrations. Maybe what we need to fix here is why the original migration overwrites the published one? The published one should be prioritize.  And I think this should be handled on the framework level? Will dig further when I got the chance.

**Comment by neuronetio** [comment]
have same problem

**Comment by yajra** [comment]
Yes, @neuronetio solution should do the trick. Sorry for late reply.
