### ISSUE TITLE
How to CRUD Permission,Role ? Please give me an example

### ISSUE THREAD

**Issue by Codingjames** [yajra/laravel-acl#36]

**Comment by yajra** [comment]
I just updated the package and released a new version (v6). The documentations were also updated. 

Hope it helps. 

https://yajrabox.com/docs/laravel-acl/master/permission
https://yajrabox.com/docs/laravel-acl/master/role
https://yajrabox.com/docs/laravel-acl/master/permission-user

**Comment by yajra** [comment]
I also added a bunch of test on the new version. See https://github.com/yajra/laravel-acl/tree/master/tests for some examples if it helps.
