### ISSUE TITLE
"Can" problem

### ISSUE THREAD

**Issue by weijinnx** [yajra/laravel-acl#8]
1. I can't use "can" method, before auth. But I need it.
For example:
```php
$user = User::findOrFail(1);
$user->can('something');
```
2. When I'm authenticated (and I'm using guards), method "can" doesn't work.
For example:
```php
auth()->guard('staff')->login($user);
auth()->guard('staff')->user()->can('something');
```
But when I get roles - they are. When I try to get permissions like that:
```php
auth()->guard('staff')->user()->permissions; // returns null
auth()->guard('staff')->user()->getPermissions(); // returns array of permissions [0 => 'permission slug']
```
I hope you will help me, thx!

**Comment by yajra** [comment]
I do use guards too and this works well for me. Can't replicate the issue using tinker with your code above.

```php
$user = User::first();
$user->can('user.view'); // true

auth()->guard('administrator')->login($user);
auth()->guard('administrator')->user()->can('user.view'); // true
```

Maybe try checking the auth user if it do exists?

```php
dd(auth()->guard('staff')->user());
```

**Comment by Vuishnak** [comment]
It exists, I checked.

**Comment by Vuishnak** [comment]
I decided to check role. This is the results:
```php
$user->isRole('root'); // true
$user->hasRole('root'); // false
```
Why?

**Comment by yajra** [comment]
@weijinnx sorry for late response. HasRole is comparing on the `name` field and not on slug. Will release a patch to fix it. Thanks!
